### ISSUE TITLE
Task Creation Fail

### ISSUE THREAD

**Issue by tankajoshi122** [granularai/geoengine-issues#6]
**Describe the bug**
Not able to create Task for Annotation

**To Reproduce**

1. Go to 'Task'
2. Click on 'Add New'
3. Fill the the required field and Click Submit
4. See error " Could not create task"

**Expected behavior**
Annotation task should be created with out error

**Screenshots**

![taskF](https://user-images.githubusercontent.com/52836788/195017281-5d933ffb-504c-400b-b539-15079b8990c4.png)

**Additional context**

**Comment by hal-shin** [comment]
I'm assuming this is related to https://github.com/granularai/geoengine-issues/issues/8 due to the timing of this issue.

The task was most likely unable to be created as it contained a tag of invalid length (at the time it was made).

Without the actual inputs to the task object, I'm unable to triage it further. If the problem arises again, please open another issue at that time.
